### ISSUE TITLE
No export to influxDB

### ISSUE THREAD

**Issue by Liwindo** [hassio-addons/addon-glances#296]
# Problem/Motivation

The export to influxDB no longer works.

## Expected behavior

The export works without issues.

## Actual behavior

No data are in the relevant influxDB DB.

The following error stack is visible in Glances:
INFO: Starting Glances...
Glances Web User Interface started on http://127.0.0.1:61209/
INFO: Starting NGinx...
Traceback (most recent call last):
  File "/usr/bin/glances", line 8, in <module>
    sys.exit(main())
  File "/usr/lib/python3.10/site-packages/glances/__init__.py", line 179, in main
    start(config=core.get_config(), args=core.get_args())
  File "/usr/lib/python3.10/site-packages/glances/__init__.py", line 108, in start
    mode = GlancesMode(config=config, args=args)
  File "/usr/lib/python3.10/site-packages/glances/standalone.py", line 45, in __init__
    self.stats = GlancesStats(config=config, args=args)
  File "/usr/lib/python3.10/site-packages/glances/stats.py", line 39, in __init__
    self.load_modules(self.args)
  File "/usr/lib/python3.10/site-packages/glances/stats.py", line 90, in load_modules
    self.load_exports(args=args)
  File "/usr/lib/python3.10/site-packages/glances/stats.py", line 162, in load_exports
    export_module = __import__(self._exports_all[export_name])
  File "/usr/lib/python3.10/site-packages/glances/exports/glances_influxdb.py", line 18, in <module>
    from influxdb import InfluxDBClient
  File "/usr/lib/python3.10/site-packages/influxdb/__init__.py", line 9, in <module>
    from .client import InfluxDBClient
  File "/usr/lib/python3.10/site-packages/influxdb/client.py", line 23, in <module>
    from six.moves.urllib.parse import urlparse
ModuleNotFoundError: No module named 'six'

## Steps to reproduce

Setup influxDB in Glances.

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by G4KCM** [comment]
Having exactly the same problem after update to Glances 0.17.0 my system is…
Home Assistant 2022.11.2
Supervisor 2022.10.2
Operating System 9.3
Frontend 20221108.0 - latest

**Comment by askpet** [comment]
Same here:
 Add-on version: 0.17.0
 You are running the latest version of this add-on.
 System: Home Assistant OS 9.3  (aarch64 / odroid-n2)
 Home Assistant Core: 2022.11.2
 Home Assistant Supervisor: 2022.10.2

**Comment by MaelJego** [comment]
Same problem after update:
Add-on version: 0.17.0
You are running the latest version of this add-on.
System: Home Assistant OS 9.3  (amd64 / generic-x86-64)
Home Assistant Core: 2022.11.2
Home Assistant Supervisor: 2022.10.2

**Comment by frenck** [comment]
fixed in #299

**Comment by Liwindo** [comment]
@frenck The Problem is still present:

 Add-on version: 0.17.1
 You are running the latest version of this add-on.
 System: Home Assistant OS 9.3  (armv7 / raspberrypi4)
 Home Assistant Core: 2022.11.2
 Home Assistant Supervisor: 2022.10.2
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
INFO: Starting Glances...
Glances Web User Interface started on http://127.0.0.1:61209/
INFO: Starting NGinx...
Traceback (most recent call last):
  File "/usr/bin/glances", line 8, in <module>
    sys.exit(main())
  File "/usr/lib/python3.10/site-packages/glances/__init__.py", line 179, in main
    start(config=core.get_config(), args=core.get_args())
  File "/usr/lib/python3.10/site-packages/glances/__init__.py", line 108, in start
    mode = GlancesMode(config=config, args=args)
  File "/usr/lib/python3.10/site-packages/glances/standalone.py", line 45, in __init__
    self.stats = GlancesStats(config=config, args=args)
  File "/usr/lib/python3.10/site-packages/glances/stats.py", line 39, in __init__
    self.load_modules(self.args)
  File "/usr/lib/python3.10/site-packages/glances/stats.py", line 90, in load_modules
    self.load_exports(args=args)
  File "/usr/lib/python3.10/site-packages/glances/stats.py", line 162, in load_exports
    export_module = __import__(self._exports_all[export_name])
  File "/usr/lib/python3.10/site-packages/glances/exports/glances_influxdb.py", line 18, in <module>
    from influxdb import InfluxDBClient
  File "/usr/lib/python3.10/site-packages/influxdb/__init__.py", line 9, in <module>
    from .client import InfluxDBClient
  File "/usr/lib/python3.10/site-packages/influxdb/client.py", line 23, in <module>
    from six.moves.urllib.parse import urlparse
ModuleNotFoundError: No module named 'six'

**Comment by G4KCM** [comment]
Indeed he problem still persists.  Tried removing and reloading the Glances add-on and reboot of HA but still no module six. Exactly the same log output as @Liwindo.

**Comment by kkellner** [comment]
Yep, same problem with `0.17.1`:

```
-----------------------------------------------------------
 Add-on: Glances
 A cross-platform system monitoring tool
-----------------------------------------------------------
 Add-on version: 0.17.1
 You are running the latest version of this add-on.
 System: Home Assistant OS 9.3  (amd64 / qemux86-64)
 Home Assistant Core: 2022.11.3
 Home Assistant Supervisor: 2022.10.2
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
INFO: Starting Glances...
Glances Web User Interface started on http://127.0.0.1:61209/
INFO: Starting NGinx...
Traceback (most recent call last):
  File "/usr/bin/glances", line 8, in <module>
    sys.exit(main())
  File "/usr/lib/python3.10/site-packages/glances/__init__.py", line 179, in main
    start(config=core.get_config(), args=core.get_args())
  File "/usr/lib/python3.10/site-packages/glances/__init__.py", line 108, in start
    mode = GlancesMode(config=config, args=args)
  File "/usr/lib/python3.10/site-packages/glances/standalone.py", line 45, in __init__
    self.stats = GlancesStats(config=config, args=args)
  File "/usr/lib/python3.10/site-packages/glances/stats.py", line 39, in __init__
    self.load_modules(self.args)
  File "/usr/lib/python3.10/site-packages/glances/stats.py", line 90, in load_modules
    self.load_exports(args=args)
  File "/usr/lib/python3.10/site-packages/glances/stats.py", line 162, in load_exports
    export_module = __import__(self._exports_all[export_name])
  File "/usr/lib/python3.10/site-packages/glances/exports/glances_influxdb.py", line 18, in <module>
    from influxdb import InfluxDBClient
  File "/usr/lib/python3.10/site-packages/influxdb/__init__.py", line 9, in <module>
    from .client import InfluxDBClient
  File "/usr/lib/python3.10/site-packages/influxdb/client.py", line 23, in <module>
    from six.moves.urllib.parse import urlparse
ModuleNotFoundError: No module named 'six'
```

**Comment by MaelJego** [comment]
No change.
Same error.

module 'six' is not installed (I have checked in the container).

-----------------------------------------------------------
 Add-on: Glances
 A cross-platform system monitoring tool
-----------------------------------------------------------
 Add-on version: 0.17.1
 You are running the latest version of this add-on.
 System: Home Assistant OS 9.3  (amd64 / generic-x86-64)
 Home Assistant Core: 2022.11.3
 Home Assistant Supervisor: 2022.10.2
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
INFO: Starting Glances...
Glances Web User Interface started on http://127.0.0.1:61209/
INFO: Starting NGinx...
Traceback (most recent call last):
  File "/usr/bin/glances", line 8, in <module>
    sys.exit(main())
  File "/usr/lib/python3.10/site-packages/glances/__init__.py", line 179, in main
    start(config=core.get_config(), args=core.get_args())
  File "/usr/lib/python3.10/site-packages/glances/__init__.py", line 108, in start
    mode = GlancesMode(config=config, args=args)
  File "/usr/lib/python3.10/site-packages/glances/standalone.py", line 45, in __init__
    self.stats = GlancesStats(config=config, args=args)
  File "/usr/lib/python3.10/site-packages/glances/stats.py", line 39, in __init__
    self.load_modules(self.args)
  File "/usr/lib/python3.10/site-packages/glances/stats.py", line 90, in load_modules
    self.load_exports(args=args)
  File "/usr/lib/python3.10/site-packages/glances/stats.py", line 162, in load_exports
    export_module = __import__(self._exports_all[export_name])
  File "/usr/lib/python3.10/site-packages/glances/exports/glances_influxdb.py", line 18, in <module>
    from influxdb import InfluxDBClient
  File "/usr/lib/python3.10/site-packages/influxdb/__init__.py", line 9, in <module>
    from .client import InfluxDBClient
  File "/usr/lib/python3.10/site-packages/influxdb/client.py", line 23, in <module>
    from six.moves.urllib.parse import urlparse
ModuleNotFoundError: No module named 'six'

![image](https://user-images.githubusercontent.com/99092881/202530435-733300b3-c5c6-4124-9c7f-125c0c0a5422.png)

**Comment by MaelJego** [comment]
> I'm not sure how to re-open this issue. Do we need to open a new issue against `0.17.1`?

Just created new issue
https://github.com/hassio-addons/addon-glances/issues/302#issue-1453817625
